version: '3.4'

services:
    accountsdb:
        image: postgres:15-alpine
        restart: always
        volumes:
            - db_postgresql:/docker-entrypoint-initdb.d
        container_name: dbpostgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "Postgres2022!"

    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes: 
            - cache:/data

volumes:
    cache:
        driver: local
    db_postgresql:
        driver: local
